// vue-app/src/pages/Watch.vue
<template>
  <div class="watch-content">
    <h2>watch page</h2>
    <div class="video"></div>
    <p class="watch-sentence">watch start</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch</p>
    <p class="watch-sentence">watch end</p>
  </div>
</template>

<script>
export default {
  name: 'Watch',
  mounted() {
    console.log(this.$route.query);
  },
};
</script>

<style scoped>
*,
::before,
::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

.watch-sentence {
  color: red;
}
</style>

// react-with-routing-app/src/pages/watch/index.js
import './index.css';
import {useLocation} from 'react-router-dom';

function Watch() {
  const q = new URLSearchParams(useLocation().search);

  const videoId = q.get('videoId');
  console.log('videoId', videoId);
  return (
    <div className="watch-content">
      <h2>watch page</h2>
      <div className="video">you see video {videoId}</div>
      <p className="watch-sentence">watch start</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch</p>
      <p className="watch-sentence">watch end</p>
    </div>
  );
}

export {Watch};
