// vue-app/src/pages/Video.vue
<template>
  <div class="video-content">
    <h2>video page</h2>
    <ul>
      <li @click="watchVideo($event, 1)">VIDEO 1</li>
      <li @click="watchVideo($event, 2)">VIDEO 2</li>
      <li @click="watchVideo($event, 3)">VIDEO 3</li>
    </ul>
    <p class="video-sentence">video start</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video</p>
    <p class="video-sentence">video end</p>
  </div>
</template>

<script>
export default {
  name: 'Video',
  methods: {
    watchVideo(event, videoId) {
      this.$router.push({path: 'watch', query: {videoId: videoId}});
      console.log(event, this.$router);
    },
  },
};
</script>

<style scoped>
*,
::before,
::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

.video-sentence {
  color: green;
}
</style>

// react-with-routing-app/src/pages/video/index.js
import './index.css';
import {Link} from 'react-router-dom';

function Video() {
  return (
    <div className="video-content">
      <h2>video page</h2>

      <ul>
        <li>
          <Link to="/watch?videoId=1">VIDEO 1</Link>
        </li>
        <li>
          <Link to="/watch?videoId=2">VIDEO 2</Link>
        </li>
        <li>
          <Link to="/watch?videoId=3">VIDEO 3</Link>
        </li>
      </ul>

      <p className="video-sentence">video start</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video</p>
      <p className="video-sentence">video end</p>
    </div>
  );
}

export {Video};
